apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: gatekeeper
  namespace: gatekeeper
spec:
  hostAPI: https://infisical.infisical.svc.cluster.local:8080/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: machine-identity-credentials
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: codeforge-s0c-c
        envSlug: prod
        secretsPath: /gatekeeper
  managedSecretReference:
    secretName: gatekeeper
    secretNamespace: gatekeeper
    creationPolicy: Owner
