apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: "*"
    helm:
      values: |
        tempo:
          storage:
            trace:
              backend: local
              local:
                path: /var/tempo/traces
          retention: 336h  # 14 days
          metricsGenerator:
            enabled: true
            remoteWriteUrl: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/write
          extraVolumeMounts:
            - name: tempo-overrides
              mountPath: /conf/overrides.yaml
              subPath: overrides.yaml
        extraVolumes:
          - name: tempo-overrides
            configMap:
              name: tempo-overrides
        persistence:
          enabled: true
          size: 50Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
