apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-overrides
  namespace: monitoring
data:
  overrides.yaml: |
    overrides:
      defaults:
        metrics_generator:
          processors:
            - service-graphs
            - span-metrics
