# Syncs Ceph CSI credentials from Infisical into the ceph-csi namespace.
# Expects two paths in Infisical:
#   /ceph/provisioner  ->  userID, userKey
#   /ceph/node         ->  userID, userKey
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: csi-rbd-provisioner-secret
  namespace: ceph-csi
spec:
  hostAPI: https://infisical.jhparker.uk/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: machine-identity-credentials
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: codeforge-s0c-c
        envSlug: prod
        secretsPath: /ceph/provisioner
  managedSecretReference:
    secretName: csi-rbd-provisioner-secret
    secretNamespace: ceph-csi
    creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: csi-rbd-node-secret
  namespace: ceph-csi
spec:
  hostAPI: https://infisical.jhparker.uk/api
  resyncInterval: 60
  authentication:
    universalAuth:
      credentialsRef:
        secretName: machine-identity-credentials
        secretNamespace: infisical-operator-system
      secretsScope:
        projectSlug: codeforge-s0c-c
        envSlug: prod
        secretsPath: /ceph/node
  managedSecretReference:
    secretName: csi-rbd-node-secret
    secretNamespace: ceph-csi
    creationPolicy: Owner
