apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: blueprints
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:

    exporters:
      otlp:
        endpoint: tempo.monitoring.svc.cluster.local:4317
        tls:
          ca_file: /etc/tls/ca.crt
      otlphttp/loki:
        endpoint: https://loki.monitoring.svc.cluster.local:3100/otlp
        tls:
          ca_file: /etc/tls/ca.crt
      prometheusremotewrite:
        endpoint: https://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/write
        tls:
          ca_file: /etc/tls/ca.crt

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/loki]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheusremotewrite]
